server:
  port: 8001
spring:
  application:
    name: cloud-payment-hystrix-service
eureka:
  client:
    #    表示向注册中心注册自己
    register-with-eureka: true
      #    是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon受用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true