spring:
  application:
    name: cloud-consumer-feign-order80
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
server:
  port: 80
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 6000
  hystrix:
    enabled: true